### PR TITLE
fix: add new validators on initial query and becomde validator tx

### LINKED ISSUE #129: `chain` service panics when validator not found, causing db `PoisonError`
On the housefire chain, the `chain` service has periodically been hanging:

```
2024-10-02T13:27:33.612715Z  INFO chain: Updating bonds for 1 addresses
thread 'tokio-runtime-worker' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/deadpool-sync-0.1.4/src/lib.rs:123:44:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
2024-10-02T13:27:33.612877Z  INFO chain: Updating unbonds for 0 addresses
2024-10-02T13:27:33.612920Z  INFO chain: Updating revealed pks for 1 addresses
2024-10-02T13:27:33.613123Z ERROR shared::error: Database error reason=Failed to interact with db
```
and
```
2024-10-03T18:10:37.606483Z  INFO chain: Inserting initial data...
thread 'tokio-runtime-worker' panicked at chain/src/repository/pos.rs:67:26:
Failed to get validator: NotFound
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2024-10-03T18:10:42.177576Z ERROR shared::error: Database error reason=Failed to interact with db
Error: Database
```

The query that causes the panic is
```
SELECT "validators"."id", "validators"."namada_address", "validators"."voting_power", "validators"."max_commission", "validators"."commission", "validators"."name", "validators"."email", "validators"."website", "validators"."description", "validators"."discord_handle", "validators"."avatar", "validators"."state" FROM "validators" WHERE ("validators"."namada_address" = $1) LIMIT $2
```

This behaviour can be triggered by initializing a new validator and immediately bonding tokens to it before it's active (which is possible with the CLI). The `chain` service will try to process the bond tx, but since the target validator is not yet present in the validators table it will result in a panic.

The `chain` service will panic/restart repeatedly until two epochs have passed and the validator has been added to the validators table, at which point it can proceed. This likely went unnoticed before because epochs were only 5 minutes on previous housefire chains (they are 1 hr on the latest chain).

### PR DESCRIPTION
**Pull request by mateuszjasiuk**
Resolves  #129

### CODE REVIEW

File: chain/src/repository/pos.rs [hunk 1]
```diff
@@ -198,6 +200,44 @@ pub fn update_validator_metadata(
     anyhow::Ok(())
 }
 
+pub fn upsert_validators(
```
Comment (mateuszjasiuk) [inline chain/src/repository/pos.rs:203]: Copied from pos service

File: chain/src/services/namada.rs [hunk 2]
```diff
@@ -596,6 +597,96 @@ pub async fn query_all_votes(
     anyhow::Ok(votes.iter().flatten().cloned().collect())
 }
 
+pub async fn get_validator_set_at_epoch(
```
Comment (mateuszjasiuk) [inline chain/src/services/namada.rs:600]: Copied from pos service

**Review by Fraccaman — APPROVED** [review]
